apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sinatra
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sinatra
  template:
    metadata:
      labels:
        run: sinatra
    spec:
      containers:
      - name: sinatra
        image: gcr.io/sinatra/test
        ports:
        - containerPort: 4567
        readinessProbe:
          httpGet:
            path: /
            port: 4567
          initialDelaySeconds: 25
          timeoutSeconds: 10
